<template>
  <div  class="columns is-multiline is-mobile">
    <div class="column is-one-third" v-for="(src, index) in imageSources" :key="index">
    <b-image
      ratio="1by1"
      class="image"
      :src="src"
      :alt="prompt"></b-image>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'nuxt-property-decorator'
import { isUrl, asBase64Image } from '@/utils/url'

@Component({})
export default class ImageGrid extends Vue {
  @Prop({ type: Array, required: false }) public images!: string[]
  @Prop({ type: String, required: false, default: 'something creative generated by AI' }) public prompt!: string[]

  get imageSources() {
    return (this.images || []).map(img => isUrl(img) ? img : asBase64Image(img))
  }
}
</script>
