<template>
  <div  class="columns is-gapless is-multiline is-mobile">
    <div class="column is-one-third" v-for="(src, index) in imageSources" :key="index">
    <SelectableImage :index="index" :src="src" @click="handleClick" @remove="handleRemove" />
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Emit, Prop, Vue } from 'nuxt-property-decorator'

const components = {
  SelectableImage: () => import('@/components/shared/view/SelectableImage.vue'),
}

@Component({ components })
export default class ImageGrid extends Vue {
  @Prop({ type: Array, required: false }) public images!: string[]
  @Prop({ type: String, required: false, default: 'something creative generated by AI' }) public prompt!: string[]
  private indexed: number[] = []

  get imageSources() {
    return (this.images || [])
  }

  protected handleClick(index: number) {
    this.indexed = [...this.indexed, index]
    this.handleUpdate(this.indexed)
  }

  protected handleRemove(index: number) {
    this.indexed = this.indexed.filter(i => i !== index)
    this.handleUpdate(this.indexed)
  }

  @Emit('update')
  private handleUpdate(indexed: number[]) {
    return indexed
  }
}
</script>
