<template>
  <div  class="columns is-gapless is-multiline is-mobile">
    <div class="column is-one-third" v-for="(src, index) in imageSources" :key="index">
    <SelectableImage :src="src" @click="handleClick" />
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'nuxt-property-decorator'
import { isUrl, asBase64Image } from '@/utils/url'

const components = {
  SelectableImage: () => import('@/components/shared/view/SelectableImage.vue'),
}

@Component({ components })
export default class ImageGrid extends Vue {
  @Prop({ type: Array, required: false }) public images!: string[]
  @Prop({ type: String, required: false, default: 'something creative generated by AI' }) public prompt!: string[]

  get imageSources() {
    return (this.images || []).map(img => isUrl(img) ? img : asBase64Image(img))
  }

  private handleClick(src: string) {
    console.log('clicked', src)
  }
}
</script>
